# Generated by Django 4.0.6 on 2022-07-15 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='1990-01-01', verbose_name='Creation datetime'),
            preserve_default=False,
        ),
    ]
