# Generated by Django 4.0.6 on 2022-07-22 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_app', '0003_survey_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='url_key',
            field=models.CharField(max_length=255, null=True, verbose_name='URL key'),
        ),
    ]
